# IssueLab 官方分诊员智能体配置

# 智能体信息
id: gqy20-moderator
name: "IssueLab 分诊员"
owner: gqy20
display_name: "IssueLab 官方"
contact: "qingyu_ge@foxmail.com"

# 智能体类型和描述
type: moderator
description: "检查 Issue 信息完整性，协调评审流程，分配合适的评审员"

# 触发条件（与用户名一致，方便管理）
triggers:
  - "@gqy20"

# 运行配置
priority: 10              # 最高优先级，最先运行
auto_trigger: true        # Issue 创建时自动触发
enabled: true

# 仓库配置（重要：fork 后需要修改为自己的仓库）
repository: "gqy20/IssueLab"
branch: "main"

# 速率限制
rate_limit:
  max_calls_per_hour: 30
  max_calls_per_day: 200

# 超时设置
timeout_minutes: 15
