name: Run Built-in Agent

description: |
  运行 IssueLab 系统 Agent（由 agents/*/agent.yml 配置驱动）
  包含环境变量配置。

inputs:
  agent-name:
    description: Agent 名称
    required: true
  issue-number:
    description: Issue 编号
    required: true
    default: ${{ github.event.issue.number }}
  gh-token:
    description: GitHub Token (PAT or default)
    required: true
  anthropic-auth-token:
    description: Anthropic Auth Token
    required: true
  anthropic-base-url:
    description: Anthropic Base URL
    required: false
    default: 'https://api.minimaxi.com/anthropic'
  anthropic-model:
    description: Anthropic Model
    required: false
    default: 'MiniMax-M2.1'

runs:
  using: composite
  steps:
    - name: Run agent
      shell: bash
      run: |
        uv run python -m issuelab execute \
          --issue ${{ inputs.issue-number }} \
          --agents ${{ inputs.agent-name }} \
          --post
      env:
        GH_TOKEN: ${{ inputs.gh-token }}
        GITHUB_TOKEN: ${{ inputs.gh-token }}
        ANTHROPIC_AUTH_TOKEN: ${{ inputs.anthropic-auth-token }}
        ANTHROPIC_BASE_URL: ${{ inputs.anthropic-base-url }}
        ANTHROPIC_MODEL: ${{ inputs.anthropic-model }}
        LOG_FILE: ${{ github.workspace }}/logs/${{ inputs.agent-name }}_${{ inputs.issue-number }}.log
        LOG_LEVEL: DEBUG
        CLAUDE_AGENT_SDK_SKIP_VERSION_CHECK: "true"
        CLAUDE_CODE_STREAM_CLOSE_TIMEOUT: "30000"
        ACTIONS_STEP_DEBUG: "true"
        ACTIONS_RUNNER_DEBUG: "true"
        MCP_LOG_DETAIL: "1"
        PROMPT_LOG: "1"
