name: Run Built-in Agent

description: |
  运行 IssueLab 内置 Agent（moderator, reviewer_a, reviewer_b, summarizer, echo）
  包含环境变量配置。

inputs:
  agent-name:
    description: Agent 名称
    required: true
  issue-number:
    description: Issue 编号
    required: true
    default: ${{ github.event.issue.number }}

runs:
  using: composite
  steps:
    - name: Run agent
      shell: bash
      run: |
        uv run python -m issuelab execute \
          --issue ${{ inputs.issue-number }} \
          --agents ${{ inputs.agent-name }} \
          --post
      env:
        GH_TOKEN: ${{ secrets.PAT_TOKEN || github.token }}
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN || github.token }}
        ANTHROPIC_AUTH_TOKEN: ${{ secrets.ANTHROPIC_AUTH_TOKEN }}
        ANTHROPIC_BASE_URL: ${{ secrets.ANTHROPIC_BASE_URL || 'https://api.minimaxi.com/anthropic' }}
        ANTHROPIC_MODEL: ${{ secrets.ANTHROPIC_MODEL || 'MiniMax-M2.1' }}
        LOG_FILE: ${{ github.workspace }}/logs/${{ inputs.agent-name }}_${{ inputs.issue-number }}.log
        LOG_LEVEL: DEBUG
        CLAUDE_AGENT_SDK_SKIP_VERSION_CHECK: "true"
        CLAUDE_CODE_STREAM_CLOSE_TIMEOUT: "30000"
        ACTIONS_STEP_DEBUG: "true"
        ACTIONS_RUNNER_DEBUG: "true"
